"""rename address

Revision ID: 5a3e4436264c
Revises: cd8b3c54bcd8
Create Date: 2024-06-04 11:40:34.610457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3e4436264c'
down_revision = 'cd8b3c54bcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # op.drop_column('departments', 'location')
    # ### end Alembic commands ###
